# Generated by Django 3.0.8 on 2020-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=30, null=True)),
                ('Phone', models.CharField(max_length=30, null=True)),
                ('Profession', models.CharField(choices=[('Student', 'student'), ('Lecturer', 'Lecturer'), ('Security', 'Security'), ('Administrator', 'Administrator')], max_length=30, null=True)),
                ('Calling_hours', models.CharField(max_length=20, null=True)),
                ('Comments', models.TextField(max_length=200, null=True)),
                ('Date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCrimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSuspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_Name', models.CharField(max_length=30, null=True)),
                ('Location', models.CharField(choices=[('SBIT', 'SBIT'), ('SCIAD', 'SCIAD'), ('SLAW', 'SLAW'), ('Cafeteria', 'Cafeteria')], max_length=30, null=True)),
                ('Dress_Code', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Details', models.TextField(max_length=200, null=True)),
                ('DatePosted', models.DateTimeField(auto_now=True, null=True)),
                ('UserProfession', models.TextField(choices=[('Student', 'student'), ('Lecturer', 'Lecturer'), ('Security', 'Security'), ('Administrator', 'Administrator')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wantedSuspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(max_length=200, null=True, upload_to='')),
                ('Dob', models.DateField()),
                ('Year_of_admission', models.CharField(max_length=200, null=True)),
                ('Intake', models.CharField(max_length=200, null=True)),
                ('Index_number', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('DatePosted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
