# Generated by Django 3.0.8 on 2020-11-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacts',
        ),
        migrations.DeleteModel(
            name='tips',
        ),
    ]
