# Generated by Django 3.0.2 on 2020-03-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='safetytips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Details', models.TextField(max_length=200, null=True)),
                ('DatePosted', models.DateTimeField(auto_now=True)),
                ('UserProfession', models.TextField(choices=[('Student', 'student'), ('Lecturer', 'Lecturer'), ('Security', 'Security'), ('Administrator', 'Administrator')], max_length=200, null=True)),
            ],
        ),
    ]
