# Generated by Django 3.0.2 on 2020-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0002_safetytips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetytips',
            name='DatePosted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
