# Generated by Django 3.0.2 on 2020-03-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0003_auto_20200306_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='safetytips',
            new_name='tips',
        ),
    ]
