# Generated by Django 3.0.2 on 2020-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0004_auto_20200311_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportSuspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_Name', models.CharField(max_length=30, null=True)),
                ('Location', models.CharField(choices=[('SBIT', 'SBIT'), ('SCIAD', 'SCIAD'), ('SLAW', 'SLAW'), ('Cafeteria', 'Cafeteria')], max_length=30, null=True)),
                ('dressCode', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
