# Generated by Django 3.0.2 on 2020-03-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0005_reportsuspect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportsuspect',
            old_name='dressCode',
            new_name='Dress_Code',
        ),
    ]
