# Generated by Django 3.0.2 on 2020-03-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0006_auto_20200311_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contactsModel',
        ),
        migrations.RenameModel(
            old_name='reportSuspect',
            new_name='reportSuspectModel',
        ),
        migrations.RenameModel(
            old_name='tips',
            new_name='tipsModel',
        ),
    ]
