# Generated by Django 3.0.2 on 2020-03-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0007_auto_20200311_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactsModel',
            new_name='contacts',
        ),
        migrations.RenameModel(
            old_name='reportSuspectModel',
            new_name='reportSuspect',
        ),
        migrations.RenameModel(
            old_name='tipsModel',
            new_name='tips',
        ),
    ]
