# Generated by Django 3.0.8 on 2020-07-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0008_auto_20200311_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='wantedSuspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('Year_of_admission', models.CharField(max_length=200, null=True)),
                ('Intake', models.CharField(max_length=200, null=True)),
                ('Index_number', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
