# Generated by Django 3.0.8 on 2020-07-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0009_wantedsuspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedsuspect',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
