# Generated by Django 3.0.8 on 2020-07-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0010_wantedsuspect_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedsuspect',
            name='DatePosted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
