# Generated by Django 3.0.8 on 2020-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0011_wantedsuspect_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedsuspect',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200),
        ),
    ]
