# Generated by Django 3.0.8 on 2020-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0012_auto_20200718_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedsuspect',
            name='picture',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
