# Generated by Django 3.0.8 on 2020-10-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0014_wantedsuspect_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedsuspect',
            name='Dob',
            field=models.DateField(),
        ),
    ]
